MODEL:
  TEXT_ENCODER:
    NAME: nli-distilroberta-base-v2
    OUTPUT: vec_text
  IMAGE_TEXT_ENCODER:
    NAME: clip-ViT-B-16
    OUTPUT: vec_img_text
  AUTO_MARKUP:
    NAME: yolov8x
    OUTPUT: tag


IMAGES_FOLDER: D:/MoscowTravelHack/moscow