MODEL:
  TEXT_ENCODER:
    NAME: nli-distilroberta-base-v2
    OUTPUT: vec_text
    TASK: encoding
  IMAGE_TEXT_ENCODER:
    NAME: clip-ViT-B-16
    OUTPUT: vec_img_text
    TASK: encoding
  DETECT:
    NAME: yolov8x
    OUTPUT: tag
    TASK: tagging
    TAGS:
      person: 0
      car: 2
      train: 6
      boat: 8
      traffic_light: 9
      fire_hydrant: 10
      parking_meter: 12
      bench: 13

IMAGES_FOLDER: D:/MoscowTravelHack/moscow