MODEL:
  TEXT_ENCODER:
    NAME: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
#    nli-distilroberta-base-v2
    OUTPUT: text_vector
    TASK: encoding
    TOPK: 20
    DEVICE: cpu
  IMAGE_ENCODER:
    NAME: clip-ViT-B-16
    OUTPUT: image_vector
    TASK: encoding
    TOPK: 20
    DEVICE: cpu
  OCR:
    NAME: EasyOCR
    OUTPUT: text
    TASK: translate
    DEVICE: cpu
    PARAGRAPH: 1
    TEXT_THRESHOLD: 0.9
  DETECT:
    NAME: yolov8m
    OUTPUT: tags
    TASK: tagging
    TAGS:
      person: 0
      car: 2
      train: 6
      boat: 8
      traffic_light: 9
      fire_hydrant: 10
      parking_meter: 12
      bench: 13
    CONF: 0.8
    DEVICE: cpu